/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface HolaInterface extends Interface {
  getFunction(nameOrSignature: "getSaludo" | "setSaludo"): FunctionFragment;

  encodeFunctionData(functionFragment: "getSaludo", values?: undefined): string;
  encodeFunctionData(functionFragment: "setSaludo", values: [string]): string;

  decodeFunctionResult(functionFragment: "getSaludo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setSaludo", data: BytesLike): Result;
}

export interface Hola extends BaseContract {
  connect(runner?: ContractRunner | null): Hola;
  waitForDeployment(): Promise<this>;

  interface: HolaInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getSaludo: TypedContractMethod<[], [string], "view">;

  setSaludo: TypedContractMethod<[nuevo: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getSaludo"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setSaludo"
  ): TypedContractMethod<[nuevo: string], [void], "nonpayable">;

  filters: {};
}
