/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Hola } from "./Hola";
export * as factories from "./factories";
export { Hola__factory } from "./factories/Hola__factory";
